name: sleap

dependencies:
- python=3.6
- numpy>=1.18.1
- attrs=19.3
- jsonpickle=1.2
- networkx
- tensorflow-gpu=2.2
- tensorboard=2.1
- scikit-learn
- h5py
- pandas
- Pillow
- Shapely
- psutil
- pyzmq
- pyyaml
- python-rapidjson
- pip
- pip:
    - scipy==1.4.1
    - opencv-python-headless==4.2.0.34
    - PySide2>=5.12.0,<=5.14.1
    - imgaug==0.3.0
    - cattrs==1.0.0rc0
    - qimage2ndarray==1.8
    - imgstore==0.2.9
    - jsmin
    - seaborn
    - scikit-video
    - pykalman==0.9.5
    - "--editable=./"
    - "--requirement=./dev_requirements.txt"
